language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"
script: ./run_tests.sh
install:
  - python setup.py -q install
  - pip install -r requirements.txt
env:
  - TRAVIS_EXECUTE_PERFORMANCE=1
notifications:
  email:
    - jason.louard.ward@gmail.com
    - samson91787@gmail.com
